### PR TITLE
Add support for php 8.0.

### PR DESCRIPTION
**Pull request by jago86**
Hey there. I just added support for php 8.0. :)

### CODE REVIEW

**Comment by marijnotte** [comment]
Can this please be merged?

**Comment by ariselseng** [comment]
@Rct567 Is there anything here you need help with for merging this?

**Comment by raspberryswwwirl** [comment]
Can we please get this PR merged? We have PHP 8 specific production code that's being held back. Rather not have to fork this repo.

**Comment by dgoring** [comment]
Please merge

**Comment by dgoring** [comment]
@jago86 it doesn't look like @Rct567 is active on github anymore maybe you should deploy your fork to package.org and we can start support it from there

**Pull request merged**
